public  class primitiveDataTypeDemo {
    public void printBasicDataType() {
string batchName ='Falcon 6';
Integer totalCandiates= 120;
Boolean isAdminComplited =true;
System.debug('batch name is ' + batchName);
System.debug('total # of candiates: ' +totalCandiates);
System.debug('admin completed? '+ isAdminComplited);  
Decimal decValue=23.01;
System.debug('Decimal:'+ decValue);
Long longValue =2147483897L;//Long Value finish with L
System.debug('Long Value:'+ longValue);
Object obj = 'This is a string';
Object obj2=10;
System.debug('object 1:'+ obj);
System.debug('Object 2 is'+obj2);

ID id1='0018c00002EwfvCAAR';
System.debug('ID number is:'+id1);

}

}
